#!/bin/sh
### BEGIN INIT INFO
# Provides:          strength-history
# Required-Start:    $mongodb
# Required-Stop:     $mongodb
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Strength History server
# Description:       See https://github.com/johvik/strength_history_server
### END INIT INFO

PATH=/bin:/usr/bin:/usr/local/bin
HOME=/root
APP_DIR=/var/www/strength_history_server
FOREVER=$APP_DIR/node_modules/.bin/forever
LOG_DIR=$APP_DIR/logs

case "$1" in
  start)
    # Create log dir
    mkdir -p $LOG_DIR
    $FOREVER --minUptime 2000 --spinSleepTime 5000 -a -l $LOG_DIR/forever.log -o $LOG_DIR/out.log -e $LOG_DIR/err.log start $APP_DIR/index.js
    ;;
  stop)
    $FOREVER stop $APP_DIR/index.js
    ;;
  restart)
    $FOREVER restart $APP_DIR/index.js
    ;;
  status)
    $FOREVER list
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 3
    ;;
esac
