#!/bin/sh
APP_DIR=/var/www/strength_history_server
FOREVER=$APP_DIR/node_modules/.bin/forever
LOG_DIR=$APP_DIR/logs/

case "$1" in
  start)
    # Create log dir
    mkdir -p $LOG_DIR
    $FOREVER --sourceDir $APP_DIR --minUptime 2000 --spinSleepTime 5000 -a -l $LOG_DIR/forever.log -o $LOG_DIR/out.log -e $LOG_DIR/err.log start index.js
    ;;
  stop)
    $FOREVER --sourceDir $APP_DIR stop index.js
    ;;
  restart)
    $FOREVER --sourceDir $APP_DIR restart index.js
    ;;
  status)
    $FOREVER list
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    ;;
esac

